[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "netlify/edge-functions" 
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"
  VITE_APP_VERSION = "0.1.0"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  framework = "#custom"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.pexels.com https://*.supabase.co; connect-src 'self' https://*.supabase.co wss://*.supabase.co;"

[[edge_functions]]
  path = "/api/privacy/*"
  function = "pii-redact"

[[edge_functions]]
  path = "/api/compliance/*"
  function = "compliance-check"

[[edge_functions]]
  path = "/api/encrypt/*"
  function = "data-encrypt"