[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "netlify/edge-functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"

[dev]
  command = "npm run dev"
  targetPort = 5173

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[[edge_functions]]
  path = "/api/privacy/*"
  function = "pii-redact"

[[edge_functions]]
  path = "/api/compliance/*"
  function = "compliance-check"

[[edge_functions]]
  path = "/api/encrypt/*"
  function = "data-encrypt"